### ISSUE TITLE
Add support for objects that do not extend from Object.prototype

### ISSUE THREAD

**Issue by djvirgen** [ifwe/monocle-api-props#2]
When using objects that don't extend from `Object.prototype`, many of the functions fail:

```
var o = Object.create(null);
o.foo = 'test foo';
var p = new MonocleProps(o);
p.get('foo'); // throws error "object.hasOwnProperty is not a function"
```

In the real world, this may happen when using `url.parse('http://...', true)` because the returned object contains a `query` property that looks like an object but does not extend from `Object.prototype`:

```
var url = require('url');
var parsed = url.parse('http://www.example.com/?a=1&b=2', true);
console.log(parsed.query.hasOwnProperty); // undefined
```

**Comment by TysonAndre** [comment]
This was done in https://github.com/ifwe/monocle-api-props/pull/1 and 0.0.4?

**Comment by djvirgen** [comment]
Thanks, missed that. Closing.
